### ISSUE TITLE
About the train process

### ISSUE THREAD

**Issue by dusongjie** [davidjaw/Domain-adaptation-object-detection-with-YOLOv8#2]
I would like to ask, during the training process, when using a custom trainer, after each epoch, is the verification set of the source domain used or the verification of both the target domain and the source domain included?

**Comment by davidjaw** [comment]
I think it depends on whether you have customize your `validate` function, i.e., [this line](https://github.com/davidjaw/Domain-adaptation-object-detection-with-YOLOv8/blob/main/train.py#L465).
If not, you don't have additional data loader nor domain-separation process, so the validation will directly apply to those data defined in your [config](https://github.com/davidjaw/Domain-adaptation-object-detection-with-YOLOv8/blob/main/data/ACDC-fog_rain.yaml#L12).

So the direct answer to your question, `after each epoch, is the verification set of the source domain used or the verification of both the target domain and the source domain included?`, is NO, only rain domain is evaluated in this case **during training**.

You can see from [here](https://github.com/davidjaw/Domain-adaptation-object-detection-with-YOLOv8/blob/main/train.py#L527-L530) that I just simply validate two domains separately after the training process is complete since I don't wanna modify the validate function lol.
